name: toplyke
description: "Vote"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  vibration: ^3.1.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_localization: ^0.3.0
  flutter_image_compress: ^2.4.0
  firebase_storage: ^12.4.1
  firebase_auth: ^5.3.4
  image_cropper: ^8.1.0
  cached_network_image: ^3.3.0
  sensors_plus: ^6.1.1
  flutter_email_sender: ^7.0.0
  cloud_functions: ^5.5.0
  mailer: ^6.4.1
  path_provider: ^2.1.5
  http: ^1.4.0
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/icon.png
    - assets/sounds/click.mp3
    - assets/sounds/click2.mp3
    
    - assets/fonts/
    
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/Avenir_Next/AvenirNextLTPro-MediumCn.otf
        - asset: assets/fonts/Avenir_Next/AvenirNextLTPro-Demi.otf
        #- asset: assets/fonts/Avenir_Next/AvenirNextLTPro-Regular.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
