name: vote_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_localization: ^0.3.0
  firebase_auth: ^5.3.4
  image_cropper: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/Avenir_Next/AvenirNextLTPro-MediumCn.otf
        - asset: assets/fonts/Avenir_Next/AvenirNextLTPro-Demi.otf
        #- asset: assets/fonts/Avenir_Next/AvenirNextLTPro-Regular.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
